username: tom
install_apps:
  - vscode
  - discord
  - thunderbird
  - steam
  - lutris
  - vlc
install_snap_apps:
  - spotify
cli_apps:
  - stow
  - bat
  - exa
  - fd
  - procs
  - sd
  - ripgrep

# used to install virtualbox host modules
linux_kernal: 515
tabby_version: 1.0.174
ansible_run_file: pia-linux-3.3.1-06924.run

devices:
  - device: /dev/nvme1n1p1
    mount: /data/games
