---
- name: Install cli packages
  pacman:
    name: "{{ cli_apps }}"
    state: latest

- name: Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
    clone: yes
    update: yes

- name: Install zsh syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: Install zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: Install Fira code nerd font
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: nerd-fonts-fira-code

- name: Install starship
  pacman:
    name: starship
    state: latest

- name: Install nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "/home/{{ username }}/.nvm"
    clone: yes
    update: yes
    version: v0.39.1

- name: clone dotfiles
  git:
    repo: git@github.com:worldofth/dotfiles.git
    dest: "/home/{{ username }}/dotfiles"
    clone: yes
    update: yes

- name: make dotfile install executable
  file:
    path: ~/dotfiles/install.sh
    mode: '+x'

- name: run dotfile install
  script: ~/dotfiles/install.sh
