---
- name: Install app packages
  pacman:
    name: "{{ install_apps }}"
    state: latest

- name: Install snap app packages
  snap:
    name: "{{ install_snap_apps }}"
    state: present

- name: Download Tabby terminal
  get_url:
    url: https://github.com/Eugeny/tabby/releases/download/v1.0.174/tabby-1.0.174-linux.pacman
    dest: "/home/{{ username }}"

- name: install Tabby
  pacman:
    name: "/home/{{ username }}/tabby-1.0.174-linux.pacman"
