---
- name: Install cli packages
  pacman:
    name: "{{ cli_apps }}"
    state: latest

- name: Install oh-my-zsh
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ username }}/.oh-my-zsh"
    clone: yes
    update: yes

- name: Install zsh syntax highlighting
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: Install zsh autosuggestions
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: Install Fira code nerd font
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: nerd-fonts-fira-code

- name: Install starship
  pacman:
    name: starship
    state: latest

- name: Install nvm
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "/home/{{ username }}/.nvm"
    clone: yes
    update: yes
    version: v0.39.1

- name: clone dotfiles
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/worldofth/dotfiles
    dest: "/home/{{ username }}/dotfiles"
    clone: yes
    update: yes

- name: make dotfile install executable
  become: yes
  become_user: "{{ username }}"
  file:
    path: "/home/{{ username }}/dotfiles/install.sh"
    mode: '+x'

- name: run dotfile install
  become: yes
  become_user: "{{ username }}"
  shell: "cd /home/{{ username }}/dotfiles/ && ./install.sh"
